In [2]:
import torch

In [19]:
x=torch.ones(2,2,requires_grad=True)
y=x+2
z=y*y*3
out=z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [20]:
out.backward()

In [22]:
print(x.grad.data)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [23]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [9]:
x=torch.ones(2,3,3)
print(x)
size=x.size()[1:]
print(size)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([3, 3])


In [10]:
for i in size:
    print(i)

3
3


In [14]:
target=torch.randn(10)
print(target,target.size())
target=target.view(1,-1)
print(target,target.size())

tensor([ 0.3025,  0.8299,  2.1045,  1.1898,  0.0482, -0.9243, -1.8805, -0.2222,
        -0.3302, -0.6051]) torch.Size([10])
tensor([[ 0.3025,  0.8299,  2.1045,  1.1898,  0.0482, -0.9243, -1.8805, -0.2222,
         -0.3302, -0.6051]]) torch.Size([1, 10])


In [4]:
import numpy as np

x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
def h(x):
    if x >4:
        return 1
    elif x<2: 
        return -1
    else :
        return 0

t=x.tolist()
t2=np.array([list(map(h,i)) for i in x.tolist()])
t2

array([[-1,  0,  0],
       [ 0,  1,  1]])

In [13]:
t=np.array([1,2,3])
np.argwhere(t==max(t))

array([[2]], dtype=int64)